# Generated by Django 2.0.5 on 2021-04-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('channel_title', models.CharField(max_length=60)),
                ('thumbnail_url', models.URLField()),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
